Update deployment_eks.yml

diff --git a/.github/workflows/deployment_eks.yml b/.github/workflows/deployment_eks.yml
--- a/.github/workflows/deployment_eks.yml
+++ b/.github/workflows/deployment_eks.yml
@@ -682,7 +682,10 @@ jobs:
         shell: bash
         run: |
           env_name=$(echo ${{ needs.config.outputs.namespace }} | sed 's/-[^-]*$//')
-          helm upgrade --install --atomic --wait --namespace $env_name --create-namespace ${{ steps.values.outputs.service_name }} .charts/charts/service -f ${{ steps.values.outputs.values }}
+          if ! helm upgrade --install --atomic --wait --namespace $env_name --create-namespace ${{ steps.values.outputs.service_name }} .charts/charts/service -f ${{ steps.values.outputs.values }}; then
+            echo "Helm upgrade/install failed. Check logs in grafana for details."
+            exit 1
+          fi
           kubectl annotate --overwrite namespace $env_name staging-factory=true
 
       - name: Extend env lifetime
